spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luobintianya/config-repo.git
          username: xxxx
          password: xxx
          basedir: E:\geecloud\gee-cloud\gee-cloud-config\basedir

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"